Feat/#14 goal setting view
Team-KeepGoEat/KeepGoEat-iOS pull request #20
Opened 2023-01-05 07:21 UTC by Gayeonchoi

## ⛏ 작업 내용

- 목표 설정 뷰 컴포넌트 구현 및 레이아웃 잡기 완료 

## 📌 PR Point!

- 내용

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 목표설정 뷰  | <img width="311" alt="스크린샷 2023-01-05 오후 4 20 08" src="https://user-images.githubusercontent.com/105284376/210723941-b5ab40e9-5895-4283-8d97-86a6724bcf81.png"> 

### ✅ Issue

Resolved #14

2023-01-05 08:13 UTC, lsh328328 commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +//    }
사용하지 않는 코드는 지워주면 좋을 것 같아요

2023-01-05 08:13 UTC, lsh328328 commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        }
같이 기기대응을 해보면 좋을 것 같아요~

2023-01-05 08:13 UTC, lsh328328 commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        }
placeholder는 텍스트 필드 편집을 시작하면 자동으로 사라지니 없어도 되는 코드인 것 같아요

2023-01-05 09:18 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        }
넹 승헌님 덕분에 코드각 더 깔끔해 졌습니댱 감쟈해용

2023-01-05 09:18 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        }
넹 adjust 추가해 보게쯉니댱

2023-01-05 09:18 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +//    }
넹 감사합니댱 ~ 헌둥짱

2023-01-05 10:50 UTC, jeongkite requested changes
진짜 성장하는 개발좌... 짱이다 깨요,,🥹💗👍
불필요한 공백이나 주석 등 코드 컨벤션 관련 리뷰는 전부 찾아 남기지 않았어요! 틀린 그림 찾기 하듯 찾아보면 좋을 것 같습니다 ㅎㅎ
고생 많으셨고 리뷰 내용 참고해 수정 부탁드려요!!

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +import SnapKit
우리가 정했던 코드 컨벤션 상, 패키지 abc 순서대로 정렬하기로 해서 요 둘이 순서 바꿔주면 좋을 것 같아요~

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        $0.text = "나의 목표를 입력해볼까요?"
여기 17번도 그렇고 23번 라인도 모든 유저 공통적으로 들어가는 문구라 Const.String에 선언해놓고 사용하면 어떨까요?? 이전에 승헌님 제안으로 문자열 하드코딩 없이 개발하기로 해서 제안드립니다~! 외에도 const 파일에 빼둘만한 것들 따로 더 체크해보면 좋을 것 같아요.

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +
56번 라인 공백 없애주세요!
MARK 주석 위쪽만 띄우기로 컨벤션 정했습니다~

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +//    }
사용하지 않는 주석은 모두 삭제하고 머지해주세요!

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        view.backgroundColor = .white
배경색 설정은 layout보다는 UI 관련 코드라 setUI 함수로 따로 빼는게 좋을 것 같아요!

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +
166번 라인 같은 불필요한 공백 지워주세요!

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
>      }
요 코드는 왜 적어두신건가요?? placeholder 사용하기 전에 쓴건가요??
지금은 필요 없는 코드 같아서요~

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        $0.textColor = .gray400
textColor는 textfield에 사용자가 입력한 내용의 색상이지 placeholder의 색상과는 달라요!
placeholder의 색상을 바꾸는 방법을 찾아보면 좋을 것 같습니다~
여기는 디자이너 분들이 짜주신 것 처럼 gray700으로 해야할 것 같아요!

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        }
같은 파일의 25번 라인에서 textColor 설정하면 요 코드는 필요 없어집니다!

2023-01-05 10:50 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        return changedText.count <= 19
이 부분에서 처리하는 일은 크게 아래 세 가지로 보이는데
1. 텍스트 존재 여부에 따라 UI 변경
2. 텍스트 글자수 20자로 제한
3. 텍스트 글자수 세서 countTextLabel 값 업데이트

이 세 가지를 모두 changedText.count값으로만 할 수 있을 것 같아요!
그래서 맨 처음 요 값을 찾아 선언해두고 사용하면 어떨지~ 제안해봅니다!
특히 173번 라인에 UI 제어 관련 조건문도 아래와 같은 값으로 통일할 수 있을 것 같아요! 
그럼 코드도 조금 더 깔끔해지지 않을지..?? 생각해봅니다!

2023-01-05 12:43 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        }
거마어영 정선배님💖

2023-01-05 12:43 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +import SnapKit
넹💖

2023-01-05 12:44 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        $0.text = "나의 목표를 입력해볼까요?"
넵 도전해보께용💖

2023-01-05 12:45 UTC, Gayeonchoi commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
> +        $0.textColor = .gray400
엥 400마자용!

2023-01-07 09:41 UTC, jeongkite approved these changes
굿굿!!

2023-01-07 09:47 UTC, merged