Feat [#17] 바텀 시트 뷰 구현
Team-KeepGoEat/KeepGoEat-iOS pull request #21
Opened 2023-01-05 07:53 UTC by lsh328328

## ⛏ 작업 내용

- 바텀 시트 뷰 구현

## 📌 PR Point!

- 내용

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 바텀시트 뷰 | ![simulator_screenshot_BA619B1A-E93C-44C1-A6B5-FAF6A7973DEA](https://user-images.githubusercontent.com/51286325/210729176-cbae55b1-8031-4988-8a7a-541e1c228f16.png) |

### ✅ Issue

Resolved #17

2023-01-06 12:07 UTC, jeongkite requested changes
수고하셨습니다... 어려운 부분 맡으셔서 고생이 많으시네요🥹💗

2023-01-06 12:07 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UILabel+.swift
> +}
ㅋㅋ 저도 쇽샥해가겠습니다 ㅋㅋㅋ

2023-01-06 12:07 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIViewController+.swift
> +    }
궁금한게 왜 요기는 completion 명시해주시고 아래 50번 라인은 안 해주신걸까여?

2023-01-06 12:07 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIViewController+.swift
>  #endif
근데 작성하신 UIViewController+ 코드 #if DEBUG 안에 들어있음 안될 것 같은데 확인 부탁드려요!!

2023-01-06 12:07 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Base/Bottom/BottomSheetView.swift
> +        self.layer.maskedCorners = [.layerMinXMinYCorner, .layerMaxXMinYCorner]
이거 제가 추가한 익스텐션 활용하면 조을 것 같아요잉~

2023-01-06 12:07 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
> +    public let editGoalButton: UIButton = UIButton().then {
이거 30, 34번줄 public 안 해도 접근 가능하지 않나요??

2023-01-06 12:07 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
> +    }
버튼도 따로 빼면 좋을 것 같아요! 근데 이번 PR엔 말고... 천천히 합쉬다

2023-01-08 07:55 UTC, Gayeonchoi reviewed
멋진 코드 잘 봤습니다 승헌님 😎

2023-01-08 08:11 UTC, jeongkite approved these changes
구구굿

2023-01-08 08:11 UTC, merged