Style/#13 Onboarding View 및 기능 구현
Team-KeepGoEat/KeepGoEat-iOS pull request #41
Opened 2023-01-09 09:38 UTC by Gayeonchoi

## ⛏ 작업 내용
<온보딩 뷰 및 기능 구현>
- 

## 📌 PR Point!

- 내용

## 📸 스크린샷

|    구현 내용    |   iPhone   |   iPad   |
| :-------------: | :----------: | :----------: |
| 화면종류 | ![Simulator Screen Recording - iPhone 8 - 2023-01-09 at 18 32 08](https://user-images.githubusercontent.com/105284376/211278188-af12f124-df2a-48f3-9116-694ff1e1f588.gif) | ![Simulator Screen Recording - iPad (10th generation) - 2023-01-09 at 18 31 17](https://user-images.githubusercontent.com/105284376/211277877-8a514cca-a511-4c2c-b18f-889ad926990f.gif) |

### ✅ Issue

Resolved #13

2023-01-09 16:46 UTC, jeongkite requested changes
고생하셨습니다!!!!! 성장하는 깨발자 덕분에 기쁘네요..🥹💗
중복되는 코드가 조금 보여서 언급했어요!
이외에도 있을 수 있으니 코드 한번 싸악 훑고 수정사항 보이면 함께 고쳐주세요~~~~!

2023-01-09 16:46 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Data/Onboarding/OnboardingDataModel.swift
> + OnboardingDataModel(title: "완벽하지 않아도 괜찮아요.", descrtiption: "노력한 날들은 빈틈없이 채워질 거예요. \n 성취의 즐거움과 뿌듯함이 오롯이 남아요.", animation: "onboarding3_1x")
이거 description 필드 줄바꿈 양 옆에 공백 들어가있는데, 중앙정렬 밀리진 않나요??
&nbsp;안녕
안녕 
요런 느낌으로 밀릴 수도 있을 것 같은데 확인 부탁드려요!

2023-01-09 16:46 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Cell/OnboardingCollectionViewCell.swift
> +        setAnimationView(lottieName: lottieName)
라인 37, 44 없애도 실행될 것 같아요! 불필요한 코드는 지워줍시다

2023-01-09 16:46 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
> +    var onboardingData: [OnboardingDataModel] = []
사용되지 않는 변수는 지워줍시다!

2023-01-09 16:46 UTC, jeongkite commented on KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
> +        $0.isUserInteractionEnabled = false
라인 47, 49에 동일한 코드가 반복되고 있어요! 하나만 남기고 지워줍시다~

2023-01-10 06:55 UTC, lsh328328 reviewed
LGTM

2023-01-10 07:38 UTC, jeongkite approved these changes
리뷰 반영 고생하셨습니다~~
그런데 OnboardingViewController 16번 라인에 아직 사용되지 않는 OnboardingDataModel 변수가 남아있어요! 요 부분까지 지우고 머지 부탁드립니다!😀

2023-01-10 07:45 UTC, merged